### PR TITLE
[SNAP-1185] Guard logging and time measurements

### PR DESCRIPTION
**Pull request by sumwale**
## What changes were proposed in this pull request?

- add explicit log-level check for some log lines in java code
  (scala code already uses logging arguments as pass-by-name)
- for System.currentTimeInMillis() calls that are used only by logging,
  guard it with the appropriate log-level check
- use System.nanoTime in a few places where duration is to be measured;
  also using a DoubleAccumulator to add results for better accuracy
- cache commonly used logging.is*Enabled flags

## How was this patch tested?

SnappyData precheckin

### CODE REVIEW

**Comment by soubhik-c** [comment]
looks good. Only one question, with DoubleAccumulator can we control the precision upto 3 digits. I think signifying upto millis precision it is right ?

**Comment by sumwale** [comment]
> with DoubleAccumulator can we control the precision upto 3 digits

DoubleAccumulator is used only for partial partition-wise results (as double millis) while final accumulated sum is converted back long millis as per the exposed Spark APIs. This is to avoid losing per-partition result accuracy for timings (with nanoTime we have that level of accuracy as opposed to currentTimeMillis which didn't have it at all).

**Comment by soubhik-c** [comment]
right. probably candidate for contribution back to spark.

**Comment by sumwale** [comment]
> right. probably candidate for contribution back to spark.

Yes, this and kryo one SNAP-1136

**Pull request merged**
