### PR TITLE
Bootstrap perf

### PR DESCRIPTION
**Pull request by ahshahid**
There is a modification in WholeStageCodegen to fix the failure of join query.
The bootstrap_perf branch is now stabilized. Pls review it. I will be merging it to snappy/branch2.0 tomorrow
reducing the generated code size when structtype has all the fields of same data type.

(Please fill in changes proposed in this fix)
## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by sumwale** [comment]
@ahshahid Can you explain these changes in a bit more detail? I can't understand what the changes to row writer are trying to accomplish and why they fix failures. Don't have any background on the "join query" failures you mentioned either.

I am very uncomfortable with those basic changes to WholestageCodegen. What's the change there trying to do and why is it required? What are the implications of that change for all other queries? Are you absolutely sure that the change will work correctly for all other query types?

Secondly, have you run and verified Spark precheckin? If there is trouble on our fork, then please apply these changes to upstream spark branch-2.0.1 and then verify precheckin. We should NEVER be merging any changes to Spark layer without that basic sanity testing.

**Comment by ahshahid** [comment]
The first change in row writers safe and unsafe is to reduce the code gen
size for struct type if all fields
are of same data type. In case of bootstrap , the struct type can go up to
100 fields. It has been observed that if the generated code string is huge
it adversely impacts perf.
The second change to me appears to be a bug in wholestage code gen. To see
the bug , pls run the quick start queries without the change. The bug is
that if node implements code gen , but support code gen is false, but the
top node still is under whole stage code gen, the child of that node, if it
does not come under input adapter , it is  a problem.

I have been inviting reviewrs to view those changes , a couple of times, I
did not get any feedback, it was a very small change.

No I HV not run the spark precheckin .  I will run that.

**Comment by ahshahid** [comment]
If the whole stage code gen is a wrong fix , then pls let me know along
wirh the correct fix, I will revert it.

**Comment by ahshahid** [comment]
To reproduce the issue in junit test, so that you can see the plan easily,
pls run AQPAccuracySuite. Do not remember exact path , will mail once in
office

**Pull request merged**
